### ISSUE TITLE
Week 3 Review Ticket (12/16)

### ISSUE THREAD

**Issue by rkwreck** [rkwreck/team_flappy_bird#21]

**Comment by chenxin-chex** [comment]
Deployment manager tangibles:
Guide has deployment policy and steps to update - [Link](https://github.com/rkwreck/team_flappy_bird/wiki/Deployment-Guide-BOF-(Tech-Talk-0.4)#policy)
Guide has Nginx config file - [Link](https://github.com/rkwreck/team_flappy_bird/wiki/Deployment-Guide-BOF-(Tech-Talk-0.4)#configure)
Guide has service file in same area - [Link](https://github.com/rkwreck/team_flappy_bird/wiki/Deployment-Guide-BOF-(Tech-Talk-0.4)#configure)

**Comment by rkwreck** [comment]
**Design Manager Tangibles**
Layout: https://github.com/rkwreck/team_flappy_bird/wiki/Wireframes
Front end feature screen:
Front end screen 2:
Front end screen 3: 

**Scrum Master Tangibles:**
ReadME: https://github.com/rkwreck/team_flappy_bird/blob/master/README.md#week-3-timebox-frq-3
Tickets in Review: https://github.com/rkwreck/team_flappy_bird/projects/1#column-16863322
Tickets in Progress: https://github.com/rkwreck/team_flappy_bird/projects/1#column-16863314

**Technical Officer Tangibles:**

**GitHub Admin Tangibles**
Commit & pull request procedure (includes branching diagram): https://github.com/rkwreck/team_flappy_bird/wiki/BOF-Github-Policy-Document-(Tech-Talk-0.3)
Branching procedure: https://github.com/rkwreck/team_flappy_bird/wiki/Deployment-Guide-BOF-(Tech-Talk-0.4)

**Comment by rkwreck** [comment]
Everyone's FRQs are in their journal, which is linked on each person's individual home pages. Direct links are on the Week 3 Timebox [here](https://github.com/rkwreck/team_flappy_bird#week-3-timebox-frq-3).

**Comment by rkwreck** [comment]
**Team Scoring:** 4/5
- Design Manager has incomplete Bootstrap layouts, however includes 3 frontend screens with design/functionality toward Project Theme
- Scrum Master has fully updated READMe, ScrumBoard & Review Ticket. 
- Technical Officer has finished most of the database but it's not fully working yet.
- Deployment Manager has everything completed and working with full approval
- Github admin has commits highlighted in the wiki, README, and review ticket, and pull requests/branching explanations

**Individual Scoring:**
Rini - 2/2, Unit 2 & 3 FRQ online
Adi - 2/2, Unit 2 & 3 FRQ online
Chenxin - 2/2, Unit 2 & 3 FRQ online
Prisha - 2/2, Unit 2 & 3 FRQ online

**Comment by jm1021** [comment]
I believe provided extra credit in your seed that you are mentioning.  Your scoring seems high and technically the FRQs are in notes.  Prisha's is protected.   I did ask that these FRQs get integrated into project.   5/7 is my score.
