### ISSUE TITLE
Chenxin Individual Ticket - FRQ Week 8 

### ISSUE THREAD

**Issue by chenxin-chex** [rkwreck/team_flappy_bird#36]
These are the things I'm required to have. You can check them off as you find them: 
[Video Explanation](https://www.loom.com/share/2c86243beaac49e68a91d1c8b46fbcad)

**1. Individual Work: _score individual on completion percentage_.**
- [ ] +90% for: 9 FRQs are under management. Management includes all the individual work from FRQ Showing 1. [Link to replit](https://replit.com/@chenxinNi/FRQWork#Main.java)
- [x] +10% for: At least 2 FRQS with input and output. (see replit link)
- [x] Tangible evidence (see videos and links)

**2. Each individual must present highlights of Individual work, Crossover analysis, and reflection. They also need to share the FRQ final product, including:**
- [ ] Github Pages/Wiki that guides user thru FRQ experience (aka create an easy-to-follow guide in Wiki pages). [Link to Wiki](https://github.com/rkwreck/team_flappy_bird/wiki/Chenxin-FRQ-Showing)
- [ ] Easy to execute runtime: one location + one menu + easy to run each FRQ. [Link to replit](https://replit.com/@chenxinNi/FRQWork#Main.java)
- [ ] Easy to find/associate Github source to each FRQ. [Link to github source](https://github.com/chenxin-chex/FRQWork)

Overall Score: 
Scored by: Prisha

**Comment by chenxin-chex** [comment]
**Comparison Analysis (Cross over with Prisha):**
1. FRQ 5 (Invitation): We both properly coded a class with constructors, setters, and getter methods, which is a strength for both of us. Prisha used different parameters for her constructor, which prevented her from having to use the "this" keyword, while I did (weakness for me). Next time, I should change the paramater variable names so that I don't have to type as much.
2. FRQ 9 part 1 (Books): We both used inheritance and overriding methods in our code, which is a strength for both of us. In the child class PictureBook, Prisha called the parent class method printBookInfo in the child class, which made her code more efficient than mine. This is a weakness on my part that I can fix.
3. FRQ 9 part 2 (Animals): We both used inheritance to code for a parent class and subsequent child class, which is a strength for both of us. I think a weakness for Prisha is that she didn't properly code her constructor, since the herbivore class still required a parameter for its diet when it should be defaulted to herbivore, as I did.

**Reflection** 
I believe my FRQs are pretty strong since they all run well and are easily accessible using one menu in replit. I have inputs for nearly all but 2 FRQs (FRQ 5 and 9). My wiki page also has my learnings from each FRQ, a video explanation, and the github source for my replit. One improvement that I can get from Prisha is organizing my files into folders for each FRQ in order to organize my replit more.

**Comment by PrishaMaiti** [comment]
(10%) More than 2 FRQs have input and output
11 FRQs are under management
(85%) All code is there and seems to be running correctly, but Main.java could have been used to organize your menu and your main method code executions.
Score: 9.5/10
