### ISSUE TITLE
Week 1 Project Approval Review Ticket

### ISSUE THREAD

**Issue by rkwreck** [rkwreck/team_flappy_bird#8]

**Comment by risaiwazaki** [comment]
Deployment has guide for other members and policy is clearly stated. 1/1

**Comment by mistylavender** [comment]
Flappy Bird Scores:
Team Score: 5/5 - has completed deployment, technicals, scrum board, design, and github contributing guidelines
Individual Scores:
Rini - Completed Scrum Board, Wiki 1/1 Management Plans, Completed Backlog
Prisha - Completed Wireframe with Brain Write and complete plan for overall project 1/1
Chenxin - Completed Themes on Wiki, missing hardware being used 0.75/1
Adi - Completed Technical Key Ideas 1/1

**Comment by jm1021** [comment]
Flappy Bird - Rini SM. 4.8/5
* Wire Frames 1/1
* 10 technicals have a variety 1/1
* Request visual on GitHub policy .9/1
* Bold concept or table concepts on deployment a bit .9/1
* Issue work is solid 1/1
